# Generated by Django 3.2.6 on 2022-04-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaksiemieszka', '0003_alter_commentrating_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
