# Generated by Django 3.2.6 on 2022-04-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaksiemieszka', '0004_alter_commentrating_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
